[DX-2787] feat: added zkevm transaction receipt acquirement method
immutable/unreal-immutable-sdk pull request #85
Opened 2024-05-21 03:40 UTC by YermekG

# Summary

Added transaction receipt method to retrieve descriptive info on the status of zkEVM transaction via transaction hash.
Updated the game bridge` index.uasset `file (built from [ts-immutable-sdk](https://github.com/immutable/ts-immutable-sdk) e79ba49)

# Customer Impact

Customers can use `ZkEvmGetTransactionReceipt` to retrieve transaction information of a given transaction hash. Also, A corresponding blueprint node `ZkEvmGetTransactionReceipt' and struct for the receipt data was added.

## Added 

## Changed

## Deprecated

## Removed

## Fixed

## Security

# Things worth calling out

# Other things to consider:

- [ ] Prefix your PR title with `feat: `, `fix: `, `chore: `, `docs: `, `refactor: ` or `test: `.
- [ ] Sample blueprints are updated with new SDK changes
- [ ] Updated public documentation with new SDK changes ([Immutable X](https://docs.immutable.com/docs/x/sdks/unreal) and [Immutable zkEVM](https://docs.immutable.com/docs/zkEVM/sdks/unreal))
- [ ] Replied to GitHub issues

2024-05-21 23:27 UTC, nattb8 requested changes

2024-05-21 23:27 UTC, nattb8 commented on Content/BlueprintSampleContent/ImtblEvmTransactionReceiptWidget4_26.uasset
0x0 is fail, you've done this
0x1 is success but if it is null the transaction is still processing...i think you need check for this too

2024-05-22 00:16 UTC, nattb8 commented on Content/BlueprintSampleContent/ImtblEvmTransactionReceiptWidget4_26.uasset
As discussed, we need to handle when the transaction is processing `status == null`. Please handle this case and update the video.

2024-05-23 05:27 UTC, YermekG commented on Content/BlueprintSampleContent/ImtblEvmTransactionReceiptWidget4_26.uasset
I added the status == null case to blueprint sample file as an example how to handle _in progress_ transaction receipt status.

2024-05-23 06:28 UTC, nattb8 approved these changes

2024-05-23 06:28 UTC, merged